[package]
name = "auto_doc"
version = "0.2.5"
edition = "2021"
authors = ["Ran-Nova <miiabigloli@gmail.com>"]
description = "A procedural attribute macro to seamlessly pull external Markdown files into your Rust item documentation."
readme = "README.md"
repository = "https://github.com/Ran-Nova/auto_doc"
documentation = "https://docs.rs/auto_doc"
homepage = "https://github.com/Ran-Nova/auto_doc"
license = "MIT"
keywords = ["macro", "documentation", "proc-macro", "markdown"]
categories = ["development-tools", "rust-patterns"]

[features]
default = []
advanced = ["dep:darling", "syn/full", "syn/printing"]

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.4", default-features = false, features = [
    "derive",
    "parsing",
] }
darling = { version = "0.24.1", optional = true }

[dev-dependencies]
trybuild = "1.0.120"

[package.metadata.docs.rs]
all-features = true

[lib]
proc-macro = true
